# примеры API-запросов

# 1. Получение всех продуктов
GET http://localhost:8000/api/v1/products/
Content-Type: application/json

###

# 2. Создание продукта
POST http://localhost:8000/api/v1/products/
Content-Type: application/json

{
  "title": "помидор",
  "description": "вкус похож на МАНДАРИН"
}

###


# 3. Обновление продукта
PATCH http://localhost:8000/api/v1/products/Мандарин/
Content-Type: application/json

{
  "description": "Самый лучший мандаринчиккк"
}

###

# 4. Удаление продукта
DELETE http://localhost:8000/api/v1/products/Мандарин/
Content-Type: application/json

###

# 5. Поиск продуктов по названию и описанию
GET http://localhost:8000/api/v1/products/?search=мандарин
Content-Type: application/json

###

# создание склада
POST http://localhost:8000/api/v1/stocks/
Content-Type: application/json

{
  "address": "Склад1",
  "positions": [
    {
      "product": 1,
      "quantity": 1000,
      "price": 120.50
    },
    {
      "product": 1,
      "quantity": 100220,
      "price": 9999
    }
  ]
}

###

# обновляем записи на складе
PATCH http://localhost:8000/api/v1/stocks/1/
Content-Type: application/json

{
  "address": "Склад333",
  "positions": [
    {
      "product": 2,
      "quantity": 1000,
      "price": 120.50
    },
    {
      "product": 2,
      "quantity": 100220,
      "price": 9999
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET http://localhost:8000/api/v1/stocks/

